[tool.poetry]
name = "roboai"
version = "0.1.0"
description = ""
authors = ["AshisGhosh <ashisghosh@live.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = ">=3.10,<3.13"
ag2 = "^0.2.21"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
